// <auto-generated />
using System;
using Afrisan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Afrisan.Api.Migrations
{
    [DbContext(typeof(AfrisanDbContext))]
    [Migration("20261004203655_AgregarOrdenTrabajo")]
    partial class AgregarOrdenTrabajo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Afrisan.Api.Models.Cilindro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacidadKg")
                        .HasColumnType("numeric");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GasRefrigeranteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoActualKg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaraKg")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoRefrigerante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoQr")
                        .IsUnique();

                    b.HasIndex("GasRefrigeranteId");

                    b.ToTable("Cilindros");
                });

            modelBuilder.Entity("Afrisan.Api.Models.GasRefrigerante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GasesRefrigerantes");
                });

            modelBuilder.Entity("Afrisan.Api.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CilindroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CilindroId");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Afrisan.Api.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("OrdenesTrabajo");
                });

            modelBuilder.Entity("Afrisan.Api.Models.Cilindro", b =>
                {
                    b.HasOne("Afrisan.Api.Models.GasRefrigerante", "GasRefrigerante")
                        .WithMany("Cilindros")
                        .HasForeignKey("GasRefrigeranteId");

                    b.Navigation("GasRefrigerante");
                });

            modelBuilder.Entity("Afrisan.Api.Models.MovimientoInventario", b =>
                {
                    b.HasOne("Afrisan.Api.Models.Cilindro", "Cilindro")
                        .WithMany()
                        .HasForeignKey("CilindroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Afrisan.Api.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Movimientos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cilindro");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("Afrisan.Api.Models.GasRefrigerante", b =>
                {
                    b.Navigation("Cilindros");
                });

            modelBuilder.Entity("Afrisan.Api.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
